// Generated by gencpp from file something_about_topic/mag.msg
// DO NOT EDIT!


#ifndef SOMETHING_ABOUT_TOPIC_MESSAGE_MAG_H
#define SOMETHING_ABOUT_TOPIC_MESSAGE_MAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace something_about_topic
{
template <class ContainerAllocator>
struct mag_
{
  typedef mag_<ContainerAllocator> Type;

  mag_()
    : header()
    , magnetic_field()
    , magnetic_field_covariance()  {
      magnetic_field_covariance.assign(0.0);
  }
  mag_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , magnetic_field(_alloc)
    , magnetic_field_covariance()  {
  (void)_alloc;
      magnetic_field_covariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _magnetic_field_type;
  _magnetic_field_type magnetic_field;

   typedef boost::array<double, 9>  _magnetic_field_covariance_type;
  _magnetic_field_covariance_type magnetic_field_covariance;





  typedef boost::shared_ptr< ::something_about_topic::mag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::something_about_topic::mag_<ContainerAllocator> const> ConstPtr;

}; // struct mag_

typedef ::something_about_topic::mag_<std::allocator<void> > mag;

typedef boost::shared_ptr< ::something_about_topic::mag > magPtr;
typedef boost::shared_ptr< ::something_about_topic::mag const> magConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::something_about_topic::mag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::something_about_topic::mag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::something_about_topic::mag_<ContainerAllocator1> & lhs, const ::something_about_topic::mag_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.magnetic_field == rhs.magnetic_field &&
    lhs.magnetic_field_covariance == rhs.magnetic_field_covariance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::something_about_topic::mag_<ContainerAllocator1> & lhs, const ::something_about_topic::mag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace something_about_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::something_about_topic::mag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::something_about_topic::mag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::something_about_topic::mag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::something_about_topic::mag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::something_about_topic::mag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::something_about_topic::mag_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::something_about_topic::mag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f3b0b43eed0c9501de0fa3ff89a45aa";
  }

  static const char* value(const ::something_about_topic::mag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f3b0b43eed0c950ULL;
  static const uint64_t static_value2 = 0x1de0fa3ff89a45aaULL;
};

template<class ContainerAllocator>
struct DataType< ::something_about_topic::mag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "something_about_topic/mag";
  }

  static const char* value(const ::something_about_topic::mag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::something_about_topic::mag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Vector3 magnetic_field\n"
"float64[9] magnetic_field_covariance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::something_about_topic::mag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::something_about_topic::mag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.magnetic_field);
      stream.next(m.magnetic_field_covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::something_about_topic::mag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::something_about_topic::mag_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "magnetic_field: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.magnetic_field);
    s << indent << "magnetic_field_covariance[]" << std::endl;
    for (size_t i = 0; i < v.magnetic_field_covariance.size(); ++i)
    {
      s << indent << "  magnetic_field_covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.magnetic_field_covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOMETHING_ABOUT_TOPIC_MESSAGE_MAG_H
